San_Diego,Watsonville=711
San_Diego,Whitecourt=3064
Calgary,San_Diego=2588
Nojales,Calgary=2735
Whitecourt,Arlington=3339
Calgary,Edmonton=299
Calgary,Vauxhall=246
Calgary,Freshno=2280
San_Diego,Whitecourt=3064
Watsonville,Calgary=2222
Calgary,Whitecourt=446
Vauxhall,Nojales=2585
Calgary,San_Diego=2588
Calgary,Edmonton=299
Watsonville,Calgary=2222
Whitecourt,Arlington=3339
Calgary,Freshno=2280
Vauxhall,San_Diego=2588
San_Diego,Watsonville=711
Vauxhall,Calexico=2414
Nojales,Calgary=2735
Calgary,Vauxhall=246
San_Diego,Whitecourt=3064
Calgary,Whitecourt=446
Whitecourt,Portland=1447
Nampa,Coaldale=1237
Edmonton,Ogden=1620
Ogden,Nampa=518
Coaldale,Calgary=227
Calgary,Freshno=2280
Whitecourt,Arlington=3339
Nojales,Vernon=889
San_Diego,Watsonville=711
Calgary,Whitecourt=446
Whitecourt,Portland=1447
Calgary,Vauxhall=246
Vernon,Calgary=2637
Calgary,San_Diego=2588
Calgary,Edmonton=299
Rock_Island,Mooresville=3767
Vauxhall,Nojales=2585
Mooresville,Calgary=3143
Vauxhall,Rock_Island=2400
Vauxhall,Calexico=2414
Watsonville,Calgary=2222
Nojales,Calgary=2735
San_Diego,Whitecourt=3064
Rock_island,Mooresville=535
Mooresville,Calgary=2896
San_Diego,Vernon=200
Calexico,Vernon=371
Ogden,Vernon=1168
#



